import type { Metadata } from 'next';
import { Merriweather, Source_Code_Pro } from 'next/font/google';
import './globals.css';
import Home from './page';

const merryWeather = Merriweather({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-title',
});

const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  weight: ['200', '300', '400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merryWeather.className} ${sourceCodePro.className} bg-snow antialiased`}>
        {children}
      </body>
    </html>
  );
}
